name: ðŸš€ Publish to GitHub Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      manualTrigger:
        description: 'Trigger a manual publish'
        default: 'false'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”„ Checkout 
        uses: actions/checkout@v4.1.1
      - name: ðŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: ðŸ“ Config publish registry
        working-directory: package
        run: echo "@BadEnd777:registry=https://npm.pkg.github.com" > .npmrc
      - name: ðŸš€ Publish to NPM
        working-directory: package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGE}}