name: ğŸš€ Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Replace with your desired branch
  workflow_dispatch:
    inputs:
      manualTrigger:
        description: 'Trigger a manual deploy'
        default: 'false'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout 
        uses: actions/checkout@v3
      - name: ğŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: ğŸ“¦ Install dependencies
        working-directory: docs
        run: npm install
      - name: ğŸ—ï¸ Build Next.js app
        working-directory: docs
        run: npm run build
      - name: ğŸš€ Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: docs  # The branch for GitHub Pages
          folder: docs/out # The folder to deploy
