name: ğŸš€ Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      manualTrigger:
        description: 'Trigger a manual publish'
        default: 'false'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        name: ğŸ”„ Checkout 

      - uses: actions/setup-node@v3
        name: ğŸ› ï¸ Setup Node.js
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm publish --access public
        name: ğŸš€ Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}